source "https://rubygems.org"

gem "bridgetown", "~> 1.3.0"
gem "puma", "~> 6.0"
gem "roda"

group :bridgetown_plugins do
  # Add any Bridgetown plugins here
end

group :development, :test do
  gem "bridgetown-core", "~> 1.3.0"
end
