source "https://rubygems.org"

gem "bridgetown", "~> 1.3.0"
gem "puma", "~> 6.0"
gem "roda"

group :bridgetown_plugins do
  gem "bridgetown-sitemap", "~> 2.0", require: true
end

group :development, :test do
  gem "bridgetown-core", "~> 1.3.0"
end

gem "bridgetown-seo-tag", "~> 6.0", group: :bridgetown_plugins
gem "playwright-ruby-client", "~> 1.40", group: :bridgetown_plugins
